routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GeneralController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Admin\Auth\AuthenticatedSessionController as AdminAuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ClientController as AdminClientController;

use App\Http\Controllers\Admin\PlanController as AdminPlanController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\StripController;
use App\Models\CustomerPayment;
use App\Http\Controllers\Admin\ErrorController;
use App\Http\Controllers\Admin\NotfoundController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\FinMktHookController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',  [GeneralController::class, 'chooseLoign'])->name('home');
Route::get('denefit-webhook', [PaymentController::class, 'addWebhookPayment'])->name('addWebhookPayment');
Route::get('update-denefit-payment', [PlanController::class, 'updateDenefitsPayment'])->name('updateDenefitsPayment');
//webhook
Route::get('stripe/event', [StripController::class, 'event'])->name('stripEvent');
Route::get('stripe/event/customer', [StripController::class, 'eventCustomer'])->name('stripEventCustomer');


Route::get('/success', [GeneralController::class, 'planFinmktSuccess'])->name('plan.finmkt.success');
Route::get('/fail', [GeneralController::class, 'planFinmktFail'])->name('plan.finmkt.fail');
Route::get('/tire1Fail', [GeneralController::class, 'tire1PlanFinmktFail'])->name('plan.tire1.fail');
Route::get('/notirefail', [GeneralController::class, 'noTirePlanFail'])->name('plan.notire.fail');

//plan iframe
Route::get('/plan/{id}', [PlanController::class, 'planIframe'])->name('planiframe');
// Route::post('/plan/iframe', [PlanController::class, 'planIframeAdd'])->name('planiframe.add');
Route::post('/plan/iframe', [PlanController::class, 'planIframeAddNew'])->name('planiframe.add');
Route::post('/plan/plaidtoken', [PlanController::class, 'plaidToken'])->name('generatePlaidToken');
Route::post('/plan/getPayment', [PlanController::class, 'getPayment'])->name('getPayment');
Route::get('/email-validation/{email}', [GeneralController::class, 'validateEmail'])->name('validateEmail');
Route::post('/add-customer-payment', [CustomerPayment::class, 'customerPay'])->name('customerPay');

//dynamic pricing
Route::get('/dynamic-pricing/iframe', [GeneralController::class, 'storePlan'])->name('iframe.store');

//admin
Route::get('/admin/login', [AdminAuthenticatedSessionController::class, 'create'])->name('admin.login');
Route::post('/admin/login', [AdminAuthenticatedSessionController::class, 'store'])->name('admin.login');
Route::prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', [AdminDashboardController::class, 'home'])->name('admin.home');
        Route::get('dashboard', [AdminDashboardController::class, 'index'])->name('admin.dashboard');
        Route::get('error', [ErrorController::class, 'error'])->name('admin.error');
        Route::get('notfound', [NotfoundController::class, 'notfound'])->name('admin.notfound');
        Route::get('my-profile', [AdminController::class, 'myProfile'])->name('admin.myProfile');
        Route::get('edit-my-profile', [AdminController::class, 'editMyProfile'])->name('admin.editMyProfile');
        Route::put('update-my-profile', [AdminController::class, 'updateMyProfile'])->name('admin.updateMyProfile');
        Route::resource('clients', AdminClientController::class);
        Route::resource('plans', AdminPlanController::class);
        Route::get('sub-admins', [AdminController::class, 'subAdmins'])->name('admin.subAdmins');
        Route::get('create-admin', [AdminController::class, 'createAdmin'])->name('admin.createAdmin');
        Route::post('store-admin', [AdminController::class, 'storeAdmin'])->name('admin.storeAdmin');
        Route::get('edit-admin/{id}', [AdminController::class, 'editAdmin'])->name('admin.editAdmin');
        Route::put('update-admin', [AdminController::class, 'updateAdmin'])->name('admin.updateAdmin');
        Route::get('/logout', [AdminController::class, 'logout'])->name('admin.logout');
    });
});

//client
Route::get('/client/login', [AuthenticatedSessionController::class, 'create'])->name('client.login');
Route::post('/client/login', [AuthenticatedSessionController::class, 'store'])->name('client.login');
Route::prefix('client')->group(function () {
    Route::group(['middleware' => 'auth:user'], function () {
        Route::get('/', [DashboardController::class, 'home'])->name('client.home');
        Route::get('/store', [ClientController::class, 'store'])->name('client.store');
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('client.dashboard');
        Route::get('my-profile', [ClientController::class, 'myProfile'])->name('client.myProfile');
        Route::get('edit-my-profile', [ClientController::class, 'editMyProfile'])->name('client.editMyProfile');
        Route::put('update-my-profile', [ClientController::class, 'updateMyProfile'])->name('client.updateMyProfile');
        Route::resource('clientplans', PlanController::class);
        Route::get('customers', [ReportController::class, 'customers'])->name('client.customers');
        Route::get('customer-payments', [ReportController::class, 'customersPaments'])->name('client.customersPaments');
        Route::get('finmkt-loan-status/{email}', [PlanController::class, 'checkFinmktLoanStatus'])->name('checkFinmktLoanStatus');
        Route::get('finmkt-payment-status/{status}/{message}', [PlanController::class, 'finmktPaymentStatus'])->name('finmktPaymentStatus');
        Route::get('/logout', [ClientController::class, 'logout'])->name('client.logout');
    });
});
Route::post('/finmkt/hook', [FinMktHookController::class, 'finMktHook'])->name('finmkt.hook');
require __DIR__ . '/auth.php';

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\CompanyDetails;
use DB;
use Validator;

class ClientController extends Controller
{
    public function index()
    {
        $role            = Role::whereName('client')->first();
        $data['clients'] = User::whereRoleId($role->id)->orderBy('id', 'DESC')->get()->toArray();
        return view('admin.client.index', ['data' => $data]);
    }
    public function create()
    {
        return view('admin.client.create');
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email'     => 'required|email|max:255|unique:users',
            'password'  => 'required|string|max:255',
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        $role       = Role::whereName('client')->first();
        $password   = Hash::make($request->password);
        $client     = new User;

        $client->role_id = $role->id;
        $client->first_name = $request->first_name;
        $client->last_name = $request->last_name;
        $client->email = $request->email;
        $client->password = $password;
        $client->stripe_public_key  = $request->stripe_public_key;
        $client->stripe_secret_key  = $request->stripe_secret_key;
        $client->plaid_public_key   = $request->plaid_public_key;
        $client->plaid_secret_key   = $request->plaid_secret_key;
        $client->webhook_url        = $request->webhook_url;
        $client->denefit_token      = $request->denefit_token;
        $client->finmkt_user_id      = $request->finmkt_user_id;
        $client->finmkt_base_url      = $request->finmkt_base_url;
        $client->finmkt_username      = $request->finmkt_username;
        $client->finmkt_password      = $request->finmkt_password;
        $client->is_dynamic_price_enabled     = $request->dynamic_pricing;
        $client->dynamic_price_key    = $request->dynamic_price_key;
        $client->save();

        if ($client) {
            return redirect()->route('clients.index')->with('success', 'New Client added successfully.');
        }
        return redirect()->back()->with('error', 'Error adding Client.');
    }
    public function show($id)
    {
        $data['client'] = User::findOrFail($id);
        $data['company'] = CompanyDetails::where('user_id',$id)->first();
        return view('admin.client.show', ['data' => $data]);
    }
    public function edit($id)
    {
        $data['client'] = User::findOrFail($id);
        $data['company'] = CompanyDetails::where('user_id',$id)->first();
        return view('admin.client.edit', ['data' => $data]);
    }
    public function update(Request $request, $id)
    {
        echo "<pre>";
        print_r($request->all());
        $client = User::findOrFail($id);
        $client->first_name = $request->first_name;
        $client->last_name  = $request->last_name;
        $client->email      = $request->email;
        $client->stripe_public_key  = $request->stripe_public_key;
        $client->stripe_secret_key  = $request->stripe_secret_key;
        $client->plaid_public_key   = $request->plaid_public_key;
        $client->plaid_secret_key   = $request->plaid_secret_key;
        $client->webhook_url        = $request->webhook_url;
        $client->denefit_token      = $request->denefit_token;
        $client->finmkt_user_id      = $request->finmkt_user_id;
        $client->finmkt_base_url      = $request->finmkt_base_url;
        $client->finmkt_username      = $request->finmkt_username;
        $client->finmkt_password      = $request->finmkt_password;
        $client->tier1_toggled      = $request->tier1_toggle;
        $client->tier2_toggled     = $request->tier2_toggle;
        $client->is_dynamic_price_enabled     = $request->dynamic_pricing;
        $client->dynamic_price_key    = $request->dynamic_price_key;
        $client->save();

        $company = CompanyDetails::updateOrCreate(['user_id'=>$id],[
            'user_id'=>$id,
            'company_name'=> $request->company_name,
            'ein_number'=> $request->company_address,
            'company_address'=> $request->ein_number,
            'city'=> $request->city,
            'state_of_incorporation'=> $request->soi,
            'zip_code'=> $request->zip_code
        ]);
        if ($client) {
            return redirect()->back()->with('success', 'Client updated successfully.');
        }
        return redirect()->back()->with('error', 'Error updating Client.');
    }
    public function destroy($id)
    {
        $client = User::findOrFail($id);
        $time = time();
        $client->status = 'deleted';
        $client->email = $client->email . "_deleted_on_" . $time;
        $client->save();
        if ($client) {
            return redirect()->route('clients.index')->with('success', "Client - $client->full_name deleted successfully.");
        }
        return redirect()->back()->with('error', 'Error deleting Client.');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\User;
use Validator;
use Illuminate\Support\Facades\Storage;


class ClientController extends Controller
{
   public function myProfile()
   {
      return view('client.profile.index');
   }
   public function editMyProfile()
   {
      return view("client.profile.edit");
   }
   public function updateMyProfile(Request $request)
   {
      $validator = Validator::make($request->all(), [
         'first_name'         => 'required|string|max:255',
         'last_name'          => 'required|string|max:255',
         'stripe_public_key'  => 'max:255',
         'stripe_secret_key'  => 'max:255',
         'plaid_public_key'   => 'max:255',
         'plaid_secret_key'   => 'max:255',
         'webhook_url'        => 'max:255',
         'denefit_token'      => 'max:255',
         'finmkt_key'         => 'max:255',
         'profile_image' => 'mimes:jpeg,jpg,png,gif'

      ]);

      if ($validator->fails()) {
         return redirect()->back()->withErrors($validator)->withInput();
      }
      if ($request->hasFile('profile_image')) {

         // $image            = $request->file('profile_image');
         // $extension        = $image->getClientOriginalExtension();
         // $ImgName          = $image->getClientOriginalName();
         // $fileNameWithoutEx= pathinfo($ImgName, PATHINFO_FILENAME);
         // $destinationPath  = public_path("/images/client");

         // if (!file_exists($destinationPath)) {
         //    //create folder
         //    mkdir($destinationPath, 0755, true);
         // }

         // $time = time();
         // $image->move($destinationPath, $fileNameWithoutEx . "_" . $time . "." . $extension);
         // $fullImagePath = $fileNameWithoutEx . "_" . $time . "." . $extension;
         // $dataToUpdate['profile_image'] = $fullImagePath;

         $dataToUpdate['profile_image'] = Storage::disk('s3')->putFile('client', $request->file('profile_image'));
      }
      $dataToUpdate['first_name']         = $request->first_name;
      $dataToUpdate['last_name']          = $request->last_name;
      // $dataToUpdate['stripe_public_key']  = $request->stripe_public_key;
      // $dataToUpdate['stripe_secret_key']  = $request->stripe_secret_key;
      // $dataToUpdate['plaid_public_key']   = $request->plaid_public_key;
      // $dataToUpdate['plaid_secret_key']   = $request->plaid_secret_key;
      // $dataToUpdate['webhook_url']        = $request->webhook_url;
      // $dataToUpdate['denefit_token']      = $request->denefit_token;
      // $dataToUpdate['finmkt_user_id']      = $request->finmkt_user_id;
      // $dataToUpdate['finmkt_base_url']      = $request->finmkt_base_url;
      // $dataToUpdate['finmkt_username']      = $request->finmkt_username;
      // $dataToUpdate['finmkt_password']      = $request->finmkt_password;

      $update = User::whereId(auth()->user()->id)->update($dataToUpdate);
      return redirect()->back()->with('success', 'Profile updated successfully.');
   }


   public function store()
   {
      return view("client.store");
   }



   public function logout()
   {
      Auth::guard('user')->logout();
      return redirect()->route('home');
   }
}

resources/views/admin/client/index.blade.php
<?php
$title = 'Clients';
?>
@extends('admin.layout.app')
@section('content')
    <?php
    $notificationService = app('App\Services\NotificationService');
    $helperService = app('App\Services\HelperService');
    $authUser = Auth()->user();
    ?>
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <h4 class="page-title">Clients</h4>
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="{{ route('admin.dashboard') }}">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:;">Clients</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">All Clients</div>
                            </div>
                            <div class="card-body">
                                @if ($message = Session::get('success'))
                                    <div class="alert alert-success alert-block" id="alert_success_session">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @endif
                                @if ($message = Session::get('error'))
                                    <div class="alert alert-danger alert-block">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @endif
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="table-responsive">
                                    <!-- <label class="float-right">
                                        search:
                                        <input type="search" class="form-control from-control-sm" id="searchdata">                                        
                                    </label> -->
                                    <table id="basic-datatablesnew" class="display mb-0 table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>First Name</th>
                                                <th>Last Name</th>
                                                <th>Email</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (count($data['clients']))
                                                @foreach ($data['clients'] as $index => $client)
                                                    <tr>
                                                        <td>{{ ++$index }}</td>
                                                        <td>{{ $client['first_name'] }}</td>
                                                        <td>{{ $client['last_name'] }}</td>
                                                        <td>{{ $client['email'] }}</td>
                                                        <td>{{ $client['status'] }}</td>
                                                        <td class="flex-section">
                                                            <a href="{{ route('clients.show', $client['id']) }}"><i
                                                                    class="fa fa-eye"></i></a>
                                                            <span>|</span>
                                                            <button type="button" title=""
                                                                class="btn btn-link btn-danger p-0"
                                                                data-original-title="Delete" data-toggle="modal"
                                                                data-target="#deleteClient-{{ $client['id'] }}"> <i
                                                                    class="fa fa-times"></i> </button>
                                                        </td>
                                                    </tr>
                                                    <!-- delete Modal -->
                                                    <div class="modal fade" id="deleteClient-{{ $client['id'] }}"
                                                        tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                                        aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title" id="exampleModalLabel">Are you
                                                                        sure want to delete this Client?</h5>
                                                                    <button type="button" class="close"
                                                                        data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    {{ $client['first_name'] }}
                                                                </div>
                                                                <div class="modal-footer">

                                                                    <form
                                                                        action="{{ route('clients.destroy', $client['id']) }}"
                                                                        method="POST">
                                                                        @method('delete')
                                                                        @csrf
                                                                        <button type="submit"
                                                                            class="btn btn-success">Confirm</button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                @endforeach()
                                            @endif()
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
@endsection()