routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GeneralController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Admin\Auth\AuthenticatedSessionController as AdminAuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ClientController as AdminClientController;

use App\Http\Controllers\Admin\PlanController as AdminPlanController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\StripController;
use App\Models\CustomerPayment;
use App\Http\Controllers\Admin\ErrorController;
use App\Http\Controllers\Admin\NotfoundController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\FinMktHookController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',  [GeneralController::class, 'chooseLoign'])->name('home');
Route::get('denefit-webhook', [PaymentController::class, 'addWebhookPayment'])->name('addWebhookPayment');
Route::get('update-denefit-payment', [PlanController::class, 'updateDenefitsPayment'])->name('updateDenefitsPayment');
//webhook
Route::get('stripe/event', [StripController::class, 'event'])->name('stripEvent');
Route::get('stripe/event/customer', [StripController::class, 'eventCustomer'])->name('stripEventCustomer');


Route::get('/success', [GeneralController::class, 'planFinmktSuccess'])->name('plan.finmkt.success');
Route::get('/fail', [GeneralController::class, 'planFinmktFail'])->name('plan.finmkt.fail');
Route::get('/tire1Fail', [GeneralController::class, 'tire1PlanFinmktFail'])->name('plan.tire1.fail');
Route::get('/notirefail', [GeneralController::class, 'noTirePlanFail'])->name('plan.notire.fail');

//plan iframe
Route::get('/plan/{id}', [PlanController::class, 'planIframe'])->name('planiframe');
// Route::post('/plan/iframe', [PlanController::class, 'planIframeAdd'])->name('planiframe.add');
Route::post('/plan/iframe', [PlanController::class, 'planIframeAddNew'])->name('planiframe.add');
Route::post('/plan/plaidtoken', [PlanController::class, 'plaidToken'])->name('generatePlaidToken');
Route::post('/plan/getPayment', [PlanController::class, 'getPayment'])->name('getPayment');
Route::get('/email-validation/{email}', [GeneralController::class, 'validateEmail'])->name('validateEmail');
Route::post('/add-customer-payment', [CustomerPayment::class, 'customerPay'])->name('customerPay');

//dynamic pricing
Route::get('/dynamic-pricing/iframe', [GeneralController::class, 'storePlan'])->name('iframe.store');

//admin
Route::get('/admin/login', [AdminAuthenticatedSessionController::class, 'create'])->name('admin.login');
Route::post('/admin/login', [AdminAuthenticatedSessionController::class, 'store'])->name('admin.login');
Route::prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', [AdminDashboardController::class, 'home'])->name('admin.home');
        Route::get('dashboard', [AdminDashboardController::class, 'index'])->name('admin.dashboard');
        Route::get('error', [ErrorController::class, 'error'])->name('admin.error');
        Route::get('notfound', [NotfoundController::class, 'notfound'])->name('admin.notfound');
        Route::get('my-profile', [AdminController::class, 'myProfile'])->name('admin.myProfile');
        Route::get('edit-my-profile', [AdminController::class, 'editMyProfile'])->name('admin.editMyProfile');
        Route::put('update-my-profile', [AdminController::class, 'updateMyProfile'])->name('admin.updateMyProfile');
        Route::resource('clients', AdminClientController::class);
        Route::resource('plans', AdminPlanController::class);
        Route::get('sub-admins', [AdminController::class, 'subAdmins'])->name('admin.subAdmins');
        Route::get('create-admin', [AdminController::class, 'createAdmin'])->name('admin.createAdmin');
        Route::post('store-admin', [AdminController::class, 'storeAdmin'])->name('admin.storeAdmin');
        Route::get('edit-admin/{id}', [AdminController::class, 'editAdmin'])->name('admin.editAdmin');
        Route::put('update-admin', [AdminController::class, 'updateAdmin'])->name('admin.updateAdmin');
        Route::get('/logout', [AdminController::class, 'logout'])->name('admin.logout');
    });
});

//client
Route::get('/client/login', [AuthenticatedSessionController::class, 'create'])->name('client.login');
Route::post('/client/login', [AuthenticatedSessionController::class, 'store'])->name('client.login');
Route::prefix('client')->group(function () {
    Route::group(['middleware' => 'auth:user'], function () {
        Route::get('/', [DashboardController::class, 'home'])->name('client.home');
        Route::get('/store', [ClientController::class, 'store'])->name('client.store');
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('client.dashboard');
        Route::get('my-profile', [ClientController::class, 'myProfile'])->name('client.myProfile');
        Route::get('edit-my-profile', [ClientController::class, 'editMyProfile'])->name('client.editMyProfile');
        Route::put('update-my-profile', [ClientController::class, 'updateMyProfile'])->name('client.updateMyProfile');
        Route::resource('clientplans', PlanController::class);
        Route::get('customers', [ReportController::class, 'customers'])->name('client.customers');
        Route::get('customer-payments', [ReportController::class, 'customersPaments'])->name('client.customersPaments');
        Route::get('finmkt-loan-status/{email}', [PlanController::class, 'checkFinmktLoanStatus'])->name('checkFinmktLoanStatus');
        Route::get('finmkt-payment-status/{status}/{message}', [PlanController::class, 'finmktPaymentStatus'])->name('finmktPaymentStatus');
        Route::get('/logout', [ClientController::class, 'logout'])->name('client.logout');
    });
});
Route::post('/finmkt/hook', [FinMktHookController::class, 'finMktHook'])->name('finmkt.hook');
require __DIR__ . '/auth.php';

app/Models/Plan.php
<?php

namespace App\Models;

use App\Scopes\SkipDeletedRecord;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Plan extends Model
{
    use HasFactory;
    protected $fillable = ['terms_and_conditions','success_url', 'down_payment', 'number_of_payment', 'youtube_video_embed_code', 'user_id', 'name', 'price', 'description', 'status', 'image'];
    protected static function booted()
    {
        static::addGlobalScope(new SkipDeletedRecord);
    }
    public function getStatusAttribute($key){
        return ucwords($key);
    }
    public function getImageAttribute($key){
        // if($key){
        //     return URL("images/client/")."/".$key;
        // }
        // else{
        //     return "";
        // }
        if($key) {
            return Storage::disk('s3')->temporaryUrl($key, now()->addMinutes(30));
        }
        return;
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/PlanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Plan;
use Illuminate\Http\Request;
use Validator;

class PlanController extends Controller
{
    public function index()
    {
        $data['plans'] = Plan::orderBy('id', 'DESC')->get();
        return view('admin.plan.index', ['data' => $data]);
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'   => 'required|string|max:255',
            'price'    => 'required|integer',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }
        $dataToAdd['name'] = $request->name;
        $dataToAdd['price'] = $request->price;
        $dataToAdd['description'] = $request->description;
        $dataToAdd['down_payment'] = $request->down_payment;
        $dataToAdd['number_of_payment'] = $request->number_of_payment;
        $dataToAdd['youtube_video_embed_code'] = $request->youtube_video_embed_code;
        $dataToAdd['user_id'] = auth()->user()->id;
        $dataToAdd['created_at'] = date('Y-m-d H:i:s');
        $dataToAdd['updated_at'] = date('Y-m-d H:i:s');
        $add = Plan::create($dataToAdd);
        return redirect()->route('plans.index')->with('success', 'Plan added successfully.');
    }
    public function create()
    {
        return view('admin.plan.create');
    }
    public function update(Request $request, $id)
    {
        $plan               = Plan::findOrFail($id);
        $plan->name         = $request->name;
        $plan->price        = $request->price;
        $plan->description  = $request->description;
        $plan->down_payment = $request->down_payment;
        $plan->number_of_payment         = $request->number_of_payment;
        $plan->youtube_video_embed_code  = $request->youtube_video_embed_code;
        $plan->status       = $request->status;
        $plan->save();
        if ($plan) {
            return redirect()->back()->with('success', 'Plan updated successfully.');
        }
        return redirect()->back()->with('error', 'Error updating Plan.');
    }
    public function edit($id)
    {
        $data['plan'] = Plan::findOrFail($id);
        return view('admin.plan.edit', ['data' => $data]);
    }
    public function show($id)
    {
        $data['plan'] = Plan::findOrFail($id);
        return view('admin.plan.show', ['data' => $data]);
    }
    public function destroy($id)
    {
        $plan = Plan::findOrFail($id);
        $plan->status = 'deleted';
        $plan->save();
        if ($plan) {
            return redirect()->route('plans.index')->with('success', "Plan - $plan->name deleted successfully.");
        }
        return redirect()->back()->with('error', 'Error deleting Plan.');
    }
}

resources/views/admin/plan/create.blade.php
<?php
$title = 'Add Plan';
?>
@extends('admin.layout.app')
@section('content')
    <?php
    $notificationService = app('App\Services\NotificationService');
    $helperService = app('App\Services\HelperService');
    $authUser = Auth()->user();
    ?>
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <h4 class="page-title">Plan</h4>
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="{{ route('admin.dashboard') }}">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:;">Create A New Plan</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">Create A New Payment Plan</div>
                            </div>
                            <div class="card-body">
                                @if ($message = Session::get('success'))
                                    <div class="alert alert-success alert-block" id="alert_success_session">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @endif
                                @if ($message = Session::get('error'))
                                    <div class="alert alert-danger alert-block">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <strong>{{ $message }}</strong>
                                    </div>s
                                @endif
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <form action="{{ route('plans.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label for="">Offer Name</label>
                                                <input required class="form-control" type="text" name="name"
                                                    placeholder="Name">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="">Offer Price</label>
                                                <input required class="form-control" type="number" name="price"
                                                    placeholder="Price">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label for="">Initial Customer Payment To Get Started</label>
                                                <input required class="form-control" type="text" name="down_payment"
                                                    placeholder="Down payment">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="">Months for Payment Installments</label>
                                                <input required class="form-control" type="number" name="number_of_payment"
                                                    placeholder="Number of payment">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label for="">Video Link [YouTube/ Vimeo/ Wistia/ Video Embed
                                                    Code)</label>
                                                <input class="form-control" type="text" name="youtube_video_embed_code"
                                                    placeholder="Youtube video embed code">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="">Offer Description (10 word limit)</label>
                                                <textarea name="description" class="form-control" placeholder="Description"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group pt-0">
                                        <button type="submit" class="btn btn-primary">Add</button>
                                    </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
@endsection()

resources/views/admin/plan/edit.blade.php
<?php
   $title = "Edit Plan";
   ?>
@extends('admin.layout.app')
@section('content')
<?php
   $notificationService = app('App\Services\NotificationService');
   $helperService = app('App\Services\HelperService');
   $authUser = Auth()->user();
   ?>
<div class="main-panel">
   <div class="content">
      <div class="page-inner">
         <div class="page-header">
            <h4 class="page-title">Plan</h4>
            <ul class="breadcrumbs">
               <li class="nav-home">
                  <a href="{{route('admin.dashboard')}}">
                  <i class="flaticon-home"></i>
                  </a>
               </li>
               <li class="separator">
                  <i class="flaticon-right-arrow"></i>
               </li>
               <li class="nav-item">
                  <a href="javascript:;">Edit A Plan</a>
               </li>
            </ul>
         </div>
         <div class="row">
            <div class="col-md-12">
               <div class="card">
                  <div class="card-header">
                     <div class="card-title">Edit Existing Payment Plan</div>
                  </div>
                  <div class="card-body">
                     @if ($message = Session::get('success'))
                     <div class="alert alert-success alert-block" id="alert_success_session">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                     </div>
                     @endif
                     @if ($message = Session::get('error'))
                     <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                     </div>
                     @endif
                     @if ($errors->any())
                     <div class="alert alert-danger">
                        <ul>
                           @foreach ($errors->all() as $error)
                           <li>{{ $error }}</li>
                           @endforeach
                        </ul>
                     </div>
                     @endif
                     <form action="{{route('plans.update', $data['plan']->id)}}" method="POST" enctype="multipart/form-data">
                        @method('put')
                        @csrf
                        <div class="form-group">
                           <div class="row">
                              <div class="col-md-6">
                                 <label for="plan_name">Offer Name</label>
                                 <input required class="form-control" type="text" id="plan_name" name="name" value="{{$data['plan']->name}}" >
                              </div>
                              <div class="col-md-6">
                                 <label for="last_name">Offer Price</label>
                                 <input required class="form-control" type="text" id="plan_price" name="price" value="{{$data['plan']->price}}" >
                              </div>
                           </div>
                        </div>
                        <div class="form-group">
                           <div class="row">
                              <div class="col-md-6">
                                 <label for="">Initial Customer Payment To Get Started</label>
                                 <input required class="form-control" type="text" name="down_payment" value="{{$data['plan']->down_payment}}">
                              </div>
                              <div class="col-md-6">
                                 <label for="">Months for Payment Installments</label>
                                 <input required class="form-control" type="number" name="number_of_payment" value="{{$data['plan']->number_of_payment}}">
                              </div>
                           </div>
                        </div>
                        <div class="form-group">
                           <div class="row">
                              <div class="col-md-6">
                                 <label for="">VSL Link [YouTube/ Vimeo/ Wistia/ Video Embed Code]</label>
                                 <input required class="form-control" type="text" name="youtube_video_embed_code" value="{{$data['plan']->youtube_video_embed_code}}">
                              </div>
                              <div class="col-md-6">
                                 <label for="status">Status</label>
                                 <select class="form-control" name="status">
                                    <option <?php if($data['plan']->status =='Active'){echo 'selected';}?> value="active">Active</option>
                                    <option <?php if($data['plan']->status =='Inactive'){echo 'selected';}?> value="inactive">Inactive</option>
                                 </select>
                              </div>
                           </div>
                        </div>
                        <div class="form-group">
                           <div class="row">
                              <div class="col-md-12">
                                 <label for="desc">Offer Description (10 word limit)</label>
                                 <textarea required class="form-control" id="desc" name="description">{{$data['plan']->description}}</textarea>
                              </div>
                           </div>
                        </div>
                        <div class="form-group">
                           <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
</div>
</div>
@endsection()

resources/views/admin/plan/index.blade.php
<?php
   $title = "Plans";
   ?>
@extends('admin.layout.app')
@section('content')
<?php
   $notificationService = app('App\Services\NotificationService');
   $helperService = app('App\Services\HelperService');
   $authUser = Auth()->user();
   ?>
<div class="main-panel">
   <div class="content">
      <div class="page-inner">
         <div class="page-header">
            <h4 class="page-title">Plans</h4>
            <ul class="breadcrumbs">
               <li class="nav-home">
                  <a href="{{route('admin.dashboard')}}">
                     <i class="flaticon-home"></i>
                  </a>
               </li>
               <li class="separator">
                  <i class="flaticon-right-arrow"></i>
               </li>
               <li class="nav-item">
                  <a href="javascript:;">Plans</a>
               </li>
            </ul>
         </div>
         <div class="row">
            <div class="col-md-12">
               <div class="card">
                  <div class="card-header">
                     <div class="">All Plans</div>
                  </div>
                  <div class="card-body">
                     @if ($message = Session::get('success'))
                     <div class="alert alert-success alert-block" id="alert_success_session">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                     </div>
                     @endif
                     @if ($message = Session::get('error'))
                     <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                     </div>
                     @endif
                     @if ($errors->any())
                     <div class="alert alert-danger">
                        <ul>
                           @foreach ($errors->all() as $error)
                           <li>{{ $error }}</li>
                           @endforeach
                        </ul>
                     </div>
                     @endif
                     <div class="row  align-items-center">
                        <div class="col-lg-12">
                           <div class="table-responsive">
                              <table id="active_table" class="table align-middle all-plan-table mb-0">
                                 <thead  class="table-secondary">
                                    <tr>
                                       <th>Offer Name</th>
                                       <th>Total Price</th>
                                       <th>Down Payment</th>
                                       <th>Actions</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                 @if(count($data['plans']))
                                 @foreach($data['plans'] as $index => $plan)
                                    <tr>
                                       <td>
                                          <div class="d-flex align-items-center gap-3 cursor-pointer">
                                             <input class="" type="checkbox">
                                             <img src="{{asset('assets/admin/theme/img/avatar-1.png')}}" class="" width="35" height="35" alt="">
                                             <div class="">
                                                <h3 class="fw-bold">{{$plan->name}}</h3>
                                             </div>
                                          </div>
                                       </td>
                                       <td>
                                          <div class="price-value">
                                             <div class="value ">
                                                <span class="currency">$</span>
                                                <span class="amount">{{$plan->price}}</span>
                                                <span class="month">{{$plan->number_of_payment}}</span>
                                             </div>
                                          </div>
                                       </td>
                                       <td>
                                          <ul class="pricing-content">
                                             <li>Number of payment</li>
                                          </ul>
                                       </td>
                                       <td>
                                          <div class="table-actions d-flex align-items-center gap-3 fs-6">
                                             <textarea name="" class="clickcopyborad" rows="30" cols="40"/>
                                                <iframe src="{{env('APP_URL')}}{{'/plan/'}}{{$plan->id}}"></iframe>
                                             </textarea>
                                             <span class="copied-tooltip animated fadeInUp">
                                                URL Copied :)
                                             </span>
                                             <!-- <input type="text" class="clickcopyborad" id="occ-clipboard"  value="{{env('APP_URL')}}{{'/plan/'}}{{$plan->id}}"> -->
                                             <a href="{{route('plans.edit', $plan->id)}}" class="">
                                                <i class="fas fa-pencil-alt"></i>
                                             </a>
                                             <button type="button" title="" class="delete-btn " data-original-title="Delete" data-toggle="modal" data-target="#deletePlan-{{$plan->id}}"> <i class="fas fa-trash-alt"></i> </button>
                                             <!-- <button class="btn btn-clipboard" data-clipboard-action="copy" data-clipboard-target="#occ-clipboard">
                                                <i class="fa fa-clone" aria-hidden="true"></i>
                                             </button> -->
                                          </div>
                                       </td>
                                    </tr>
                                    @endforeach
                                    @endif()
                                 </tbody>
                              </table>
                           </div>
                        </div>
                        <!-- delete Modal -->
                        <div class="modal fade" id="deletePlan-{{$plan->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                           <div class="modal-dialog" role="document">
                              <div class="modal-content">
                                 <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Are you sure want to delete this Plan?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                       <span aria-hidden="true">&times;</span>
                                    </button>
                                 </div>
                                 <div class="modal-body">
                                    {{$plan->name}}
                                 </div>
                                 <div class="modal-footer">
                                    <form action="{{route('plans.destroy', $plan->id)}}" method="POST">
                                       @method('delete')
                                       @csrf
                                       <button type="submit" class="btn btn-success">Confirm</button>
                                    </form>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection()