routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GeneralController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Admin\Auth\AuthenticatedSessionController as AdminAuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ClientController as AdminClientController;

use App\Http\Controllers\Admin\PlanController as AdminPlanController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\StripController;
use App\Models\CustomerPayment;
use App\Http\Controllers\Admin\ErrorController;
use App\Http\Controllers\Admin\NotfoundController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\FinMktHookController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',  [GeneralController::class, 'chooseLoign'])->name('home');
Route::get('denefit-webhook', [PaymentController::class, 'addWebhookPayment'])->name('addWebhookPayment');
Route::get('update-denefit-payment', [PlanController::class, 'updateDenefitsPayment'])->name('updateDenefitsPayment');
//webhook
Route::get('stripe/event', [StripController::class, 'event'])->name('stripEvent');
Route::get('stripe/event/customer', [StripController::class, 'eventCustomer'])->name('stripEventCustomer');


Route::get('/success', [GeneralController::class, 'planFinmktSuccess'])->name('plan.finmkt.success');
Route::get('/fail', [GeneralController::class, 'planFinmktFail'])->name('plan.finmkt.fail');
Route::get('/tire1Fail', [GeneralController::class, 'tire1PlanFinmktFail'])->name('plan.tire1.fail');
Route::get('/notirefail', [GeneralController::class, 'noTirePlanFail'])->name('plan.notire.fail');

//plan iframe
Route::get('/plan/{id}', [PlanController::class, 'planIframe'])->name('planiframe');
// Route::post('/plan/iframe', [PlanController::class, 'planIframeAdd'])->name('planiframe.add');
Route::post('/plan/iframe', [PlanController::class, 'planIframeAddNew'])->name('planiframe.add');
Route::post('/plan/plaidtoken', [PlanController::class, 'plaidToken'])->name('generatePlaidToken');
Route::post('/plan/getPayment', [PlanController::class, 'getPayment'])->name('getPayment');
Route::get('/email-validation/{email}', [GeneralController::class, 'validateEmail'])->name('validateEmail');
Route::post('/add-customer-payment', [CustomerPayment::class, 'customerPay'])->name('customerPay');

//dynamic pricing
Route::get('/dynamic-pricing/iframe', [GeneralController::class, 'storePlan'])->name('iframe.store');

//admin
Route::get('/admin/login', [AdminAuthenticatedSessionController::class, 'create'])->name('admin.login');
Route::post('/admin/login', [AdminAuthenticatedSessionController::class, 'store'])->name('admin.login');
Route::prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', [AdminDashboardController::class, 'home'])->name('admin.home');
        Route::get('dashboard', [AdminDashboardController::class, 'index'])->name('admin.dashboard');
        Route::get('error', [ErrorController::class, 'error'])->name('admin.error');
        Route::get('notfound', [NotfoundController::class, 'notfound'])->name('admin.notfound');
        Route::get('my-profile', [AdminController::class, 'myProfile'])->name('admin.myProfile');
        Route::get('edit-my-profile', [AdminController::class, 'editMyProfile'])->name('admin.editMyProfile');
        Route::put('update-my-profile', [AdminController::class, 'updateMyProfile'])->name('admin.updateMyProfile');
        Route::resource('clients', AdminClientController::class);
        Route::resource('plans', AdminPlanController::class);
        Route::get('sub-admins', [AdminController::class, 'subAdmins'])->name('admin.subAdmins');
        Route::get('create-admin', [AdminController::class, 'createAdmin'])->name('admin.createAdmin');
        Route::post('store-admin', [AdminController::class, 'storeAdmin'])->name('admin.storeAdmin');
        Route::get('edit-admin/{id}', [AdminController::class, 'editAdmin'])->name('admin.editAdmin');
        Route::put('update-admin', [AdminController::class, 'updateAdmin'])->name('admin.updateAdmin');
        Route::get('/logout', [AdminController::class, 'logout'])->name('admin.logout');
    });
});

//client
Route::get('/client/login', [AuthenticatedSessionController::class, 'create'])->name('client.login');
Route::post('/client/login', [AuthenticatedSessionController::class, 'store'])->name('client.login');
Route::prefix('client')->group(function () {
    Route::group(['middleware' => 'auth:user'], function () {
        Route::get('/', [DashboardController::class, 'home'])->name('client.home');
        Route::get('/store', [ClientController::class, 'store'])->name('client.store');
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('client.dashboard');
        Route::get('my-profile', [ClientController::class, 'myProfile'])->name('client.myProfile');
        Route::get('edit-my-profile', [ClientController::class, 'editMyProfile'])->name('client.editMyProfile');
        Route::put('update-my-profile', [ClientController::class, 'updateMyProfile'])->name('client.updateMyProfile');
        Route::resource('clientplans', PlanController::class);
        Route::get('customers', [ReportController::class, 'customers'])->name('client.customers');
        Route::get('customer-payments', [ReportController::class, 'customersPaments'])->name('client.customersPaments');
        Route::get('finmkt-loan-status/{email}', [PlanController::class, 'checkFinmktLoanStatus'])->name('checkFinmktLoanStatus');
        Route::get('finmkt-payment-status/{status}/{message}', [PlanController::class, 'finmktPaymentStatus'])->name('finmktPaymentStatus');
        Route::get('/logout', [ClientController::class, 'logout'])->name('client.logout');
    });
});
Route::post('/finmkt/hook', [FinMktHookController::class, 'finMktHook'])->name('finmkt.hook');
require __DIR__ . '/auth.php';

resources/views/admin/layout/app.blade.php
@include('admin.layout.header')
@yield('content')
@include('admin.layout.footer')

resources/views/admin/layout/asset-app.blade.php
@include('admin.layout.assets-header')
@yield('content')
@include('admin.layout.assets-footer')

resources/views/admin/layout/assets-footer.blade.php
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script>
	var appUrl = '<?php echo url("/"); ?>';
</script>
<script src="{{asset('assets/admin/custom.js')}}"></script>
<script src="//cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
<script>


	$('.clickcopyborad').click(function() {
		
		/* Get the text field */
	var copyText = $(this);

	var $temp = $("<input>");
  $("body").append($temp);
  $temp.val($(copyText).val()).select();
  document.execCommand("copy");	
 
	});

</script>
</div>
</div>

<!--   Core JS Files   -->
<script src="{{asset('assets/admin/theme/js/core/jquery.3.2.1.min.js')}}"></script>
<script src="{{asset('assets/admin/theme/js/core/popper.min.js')}}"></script>
<script src="{{asset('assets/admin/theme/js/core/bootstrap.min.js')}}"></script>

<!-- jQuery UI -->
<script src="{{asset('assets/admin/theme/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js')}}"></script>
<script src="{{asset('assets/admin/theme/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')}}"></script>

<!-- jQuery Scrollbar -->
<script src="{{asset('assets/admin/theme/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js')}}"></script>


<!-- Chart JS -->
<script src="{{asset('assets/admin/theme/js/plugin/chart.js/chart.min.js')}}"></script>

<!-- jQuery Sparkline -->
<script src="{{asset('assets/admin/theme/js/plugin/jquery.sparkline/jquery.sparkline.min.js')}}"></script>

<!-- Chart Circle -->
<script src="{{asset('assets/admin/theme/js/plugin/chart-circle/circles.min.js')}}"></script>

<!-- Datatables -->
<script src="{{asset('assets/admin/theme/js/plugin/datatables/datatables.min.js')}}"></script>

<!-- Bootstrap Notify -->
<script src="{{asset('assets/admin/theme/js/plugin/bootstrap-notify/bootstrap-notify.min.js')}}"></script>

<!-- jQuery Vector Maps -->

<!-- Sweet Alert -->
<script src="{{asset('assets/admin/theme/js/plugin/sweetalert/sweetalert.min.js')}}"></script>

<!-- Atlantis JS -->
<script src="{{asset('assets/admin/theme/js/atlantis.min.js')}}"></script>

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="{{asset('assets/admin/theme/js/setting-demo.js')}}"></script>
<script src="{{asset('assets/admin/theme/js/demo.js')}}"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script> -->
<script>
	$(document).ready(function() {
		$('#basic-datatables').DataTable({});
	});
	// for copy text
	$( document ).ready(function() {

	new ClipboardJS('.btn-clipboard');

	});
	$(function(){
        $(document).on('click','iframe',function(){ this.select(); });
    });
	
</script>
<script type="text/javascript">
function select_all()
	{
		var text_val = document.getElementById('t1');
		text_val.focus();
		text_val.select();
		document.execCommand("Copy");
	}
</script>
</body>

</html>

resources/views/admin/layout/assets-header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title> Admin OCC - <?php echo ((isset($title)) ? $title : 'Home'); ?></title>
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
	<link rel="icon" href="{{asset('assets/admin/theme/img/cc-logo.png')}}" type="image/x-icon" />
	<link rel="stylesheet" href="{{asset('assets/admin/custom.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/fonts.min.css')}}">
	<!-- Fonts and icons -->
	<script src="{{asset('assets/admin/theme/js/plugin/webfont/webfont.min.js')}}"></script>
	<script src="{{asset('assets/admin/theme/js/clipboard.min.js')}}"></script>
	<script>
		WebFont.load({
			google: {
				"families": ["Lato:300,400,700,900"]
			},
			custom: {
				"families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"],
				urls: ['../assets/css/fonts.min.css']
			},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>

	<!-- CSS Files -->
	<link rel="stylesheet" href="{{asset('assets/admin/theme/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/admin/theme/css/atlantis.min.css')}}">

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link rel="stylesheet" href="{{asset('assets/admin/theme/css/demo.css')}}">
</head>
<style>
	.logo-header {
		box-shadow: none;
		border-bottom:none;
	}
	.btn-lg{
		border-radius:30px;
	}
</style>
<!-- denifit_dashboard start -->
<body class="denifit_dashboard page-not-found">

	<div class="main-header">
		<!-- Logo Header -->
		<div class="logo-header" data-background-color="blue">
			<a href="{{route('admin.dashboard')}}" class="logo">
				<img src="{{asset('assets/admin/theme/img/cc-logo.png')}}" alt="navbar brand" class="navbar-brand" width="66px">
			</a>
		</div>
		<!-- End Logo Header -->

		<!-- Navbar Header -->
		<nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">
			<div class="container-fluid">
				<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
					<li class="nav-item dropdown hidden-caret">
						<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
							<div class="avatar-sm">
								<img src="{{asset('assets/admin/theme/img/profile_placeholder.png')}}" alt="..." class="avatar-img rounded-circle">
							</div>
						</a>
						<ul class="dropdown-menu dropdown-user animated fadeIn">
							<div class="dropdown-user-scroll scrollbar-outer">
								<li>
									<div class="user-box">
										<div class="avatar-lg"><img src="{{asset('assets/admin/theme/img/profile_placeholder.png')}}" alt="image profile" class="avatar-img rounded"></div>
										<div class="u-text">
											<h4>{{auth()->user()->full_name}}</h4>
											<p class="text-muted">{{auth()->user()->email}}</p><a href="{{route('admin.editMyProfile')}}" class="btn btn-xs btn-secondary btn-sm">Edit Profile</a>
										</div>
									</div>
								</li>
								<li>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="{{route('admin.myProfile')}}">My Profile</a>
									<a class="dropdown-item" href="{{route('admin.logout')}}">Logout</a>
								</li>
							</div>
						</ul>
					</li>
				</ul>
			</div>
		</nav>
	</div>

resources/views/admin/layout/footer.blade.php
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script>
	var appUrl = '<?php echo url("/"); ?>';
</script>
<script src="{{asset('assets/admin/custom.js')}}"></script>
<script src="//cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
<script>

	$( ".datetimepicker1" ).datepicker({ minDate: 0});

	$("#datetimepicker1").datepicker({ 
		minDate: startdate,
		yearRange: '1970:2050', 
	}); 

	$('.clickcopyborad').click(function() {
		
		/* Get the text field */
	var copyText = $(this);

	var $temp = $("<input>");
		$("body").append($temp);
		$temp.val($(copyText).val()).select();
		document.execCommand("copy");	
	});

</script>
</div>
</div>

<!--   Core JS Files   -->
<script src="{{asset('assets/admin/theme/js/core/jquery.3.2.1.min.js')}}"></script>
<script src="{{asset('assets/admin/theme/js/core/popper.min.js')}}"></script>
<script src="{{asset('assets/admin/theme/js/core/bootstrap.min.js')}}"></script>

<!-- jQuery UI -->
<script src="{{asset('assets/admin/theme/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js')}}"></script>
<script src="{{asset('assets/admin/theme/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')}}"></script>

<!-- jQuery Scrollbar -->
<script src="{{asset('assets/admin/theme/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js')}}"></script>

<!-- Chart JS -->
<script src="{{asset('assets/admin/theme/js/plugin/chart.js/chart.min.js')}}"></script>

<!-- jQuery Sparkline -->
<script src="{{asset('assets/admin/theme/js/plugin/jquery.sparkline/jquery.sparkline.min.js')}}"></script>

<!-- Chart Circle -->
<script src="{{asset('assets/admin/theme/js/plugin/chart-circle/circles.min.js')}}"></script>

<!-- Datatables -->
<script src="{{asset('assets/admin/theme/js/plugin/datatables/datatables.min.js')}}"></script>

<!-- Bootstrap Notify -->
<script src="{{asset('assets/admin/theme/js/plugin/bootstrap-notify/bootstrap-notify.min.js')}}"></script>

<!-- jQuery Vector Maps -->

<!-- Sweet Alert -->
<script src="{{asset('assets/admin/theme/js/plugin/sweetalert/sweetalert.min.js')}}"></script>

<!-- Atlantis JS -->
<script src="{{asset('assets/admin/theme/js/atlantis.min.js')}}"></script>

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="{{asset('assets/admin/theme/js/setting-demo.js')}}"></script>
<script src="{{asset('assets/admin/theme/js/demo.js')}}"></script>
<script src="cdn.datatables.net/1.13.2/js/jquery.dataTables.min.js"></script>

<script>
	// $(document).ready(function() {
	// 	var dtable = $('#basic-datatables').DataTable({dom: 'lrt'});
	// 	$("#searchdata").on( 'keyup', function () {
	// 		dtable.search( this.value ).draw();
	// 	} );
	// });

	$(document).ready( function () {
		$('#basic-datatablesnew').DataTable();
	} );
	
</script>
<script type="text/javascript">
	$(document).ready(function(){
		setTimeout(function(){
		$('.clickcopyborad').click(function(){
			$('.clickcopyborad').removeClass("active");
			$(this).addClass("active");
			
		});
	},100)
	});

	
	
</script>
<!-- Usetiful script start -->
<script>
// (function (w, d, s) {
//     var a = d.getElementsByTagName('head')[0];
//     var r = d.createElement('script');
//     r.async = 1;
//     r.src = s;
//     r.setAttribute('id', 'usetifulScript');
//     r.dataset.token = "3ede2af117bcee2841625c1ffde6da2a";
//                         a.appendChild(r);
//   })(window, document, "https://www.usetiful.com/dist/usetiful.js");
</script>

<!-- Usetiful script end -->

</body>

</html>

resources/views/admin/layout/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title> Admin OCC - <?php echo ((isset($title)) ? $title : 'Home'); ?></title>
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
	<link rel="icon" href="{{asset('assets/admin/theme/img/cc-logo.png')}}" type="image/x-icon" />
	<link rel="stylesheet" href="{{asset('assets/admin/custom.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/fonts.min.css')}}">
	<link href="{{asset('assets/admin/theme/css/the-datepicker.css')}}" rel="stylesheet">
	<!-- Fonts and icons -->
	<script src="{{asset('assets/admin/theme/js/plugin/webfont/webfont.min.js')}}"></script>
	<script src="{{asset('assets/admin/theme/js/clipboard.min.js')}}"></script>
	<script src="cdn.datatables.net/1.13.2/css/jquery.dataTables.min.css"></script>
	<script>
		WebFont.load({
			google: {
				"families": ["Lato:300,400,700,900"]
			},
			custom: {
				"families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"],
				urls: ['../assets/css/fonts.min.css']
			},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>

	<!-- CSS Files -->
	<link rel="stylesheet" href="{{asset('assets/admin/theme/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/admin/theme/css/atlantis.min.css')}}">

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link rel="stylesheet" href="{{asset('assets/admin/theme/css/demo.css')}}">
</head>
<!-- denifit_dashboard start -->
<body class="denifit_dashboard">

	<div class="main-header">
		<!-- Logo Header -->
		<div class="logo-header" data-background-color="blue">
			<a href="{{route('admin.dashboard')}}" class="logo">
				<img src="{{asset('assets/admin/theme/img/cc-logo.png')}}" alt="navbar brand" class="navbar-brand" width="66px">
			</a>
			
		</div>
		<!-- End Logo Header -->

		<!-- Navbar Header -->
		<nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">
			<div class="container-fluid">
				<div class="collapse" id="search-nav">
					<!-- <form class="navbar-left navbar-form nav-search mr-md-3">
						<div class="input-group">
							<div class="input-group-prepend">
								<button type="submit" class="btn btn-search pr-1">
									<i class="fa fa-search search-icon"></i>
								</button>
							</div>
							<input type="text" placeholder="Type here to search" class="form-control">
						</div>
					</form> -->
				</div>
				<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
					<li class="nav-item toggle-nav-search hidden-caret">
						<a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
							<i class="fas fa-search"></i>
						</a>
					</li>

					<!-- <li class="nav-item dropdown hidden-caret">
						<a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fa fa-bell"></i>
							<span class="notification">4</span>
						</a>
						<ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
							<li>
								<div class="dropdown-title">No new notification</div>
							</li>

							<li>
								<a class="see-all" href="javascript:void(0);">See all notifications<i class="fa fa-angle-right"></i> </a>
							</li>
						</ul>
					</li> -->
					<!-- <li class="nav-item dropdown hidden-caret">
						<a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
							<i class="fas fa-layer-group"></i>
						</a>
						<div class="dropdown-menu quick-actions quick-actions-info animated fadeIn">
							<div class="quick-actions-header">
								<span class="title mb-1">Quick Actions</span>
								<span class="subtitle op-8">Shortcuts</span>
							</div>
							<div class="quick-actions-scroll scrollbar-outer">
								<div class="quick-actions-items">
									<div class="row m-0">
										<a class="col-6 col-md-4 p-0" href="">
											<div class="quick-actions-item">
												<i class="flaticon-pen"></i>
												<span class="text">Create Client</span>
											</div>
										</a>
									</div>
								</div>
							</div>
						</div>
					</li> -->
					<li class="nav-item dropdown hidden-caret">
						<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
							<div class="avatar-sm">
							@if(auth()->user()->profile_image)
                            <img src="{{auth()->user()->profile_image}}" class="avatar-img rounded-circle">
                            @else
							<img src="{{asset('assets/admin/theme/img/profile_placeholder.png')}}" alt="..." class="avatar-img rounded-circle">

                            @endif
							</div>
						</a>
						<ul class="dropdown-menu dropdown-user animated fadeIn">
							<div class="dropdown-user-scroll scrollbar-outer">
								<li>
									<div class="user-box">
										<div class="avatar-lg"><img src="{{asset(auth()->user()->profile_image ?? 'assets/admin/theme/img/profile_placeholder.png')}}" alt="image profile" class="avatar-img rounded"></div>
										<div class="u-text">
											<h4>{{auth()->user()->full_name}}</h4>
											<p class="text-muted">{{auth()->user()->email}}</p><a href="{{route('admin.editMyProfile')}}" class="btn btn-xs btn-secondary btn-sm">Edit Profile</a>
										</div>
									</div>
								</li>
								<li>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="{{route('admin.myProfile')}}">My Profile</a>
									<a class="dropdown-item" href="{{route('admin.logout')}}">Logout</a>
								</li>
							</div>
						</ul>
					</li>
				</ul>
			</div>
		</nav>
		<!-- End Navbar -->
	</div>

	<!-- Sidebar -->
	<div class="sidebar sidebar-style-2">
		<div class="sidebar-wrapper scrollbar scrollbar-inner">
			<div class="sidebar-content">
				<div class="user">
					<div class="avatar-sm float-left mr-2">
						@if(auth()->user()->profile_image)
                        <img src="{{auth()->user()->profile_image}}" class="avatar-img rounded-circle">
                        @else
						<img src="{{asset('assets/admin/theme/img/profile_placeholder.png')}}" alt="..." class="avatar-img rounded-circle">
                        @endif

					</div>
					<div class="info">
						<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
							<span>
								{{auth()->user()->full_name}}
								<span class="user-level">Administrator</span>
								<span class="caret"></span>
							</span>
						</a>
						<div class="clearfix"></div>
						<div class="collapse in" id="collapseExample">
							<ul class="nav">
								<li>
									<a href="{{route('admin.myProfile')}}">
										<span class="link-collapse">My Profile</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<ul class="nav nav-primary">
					<li class="nav-item active">
						<a data-toggle="collapse" href="#dashboard" class="collapsed" aria-expanded="false">
							<i class="fas fa-home"></i>
							<p>Dashboard</p>
							<span class="caret"></span>
						</a>
						<div class="collapse" id="dashboard">
							<ul class="nav nav-collapse">

								<li>
									<a href="{{route('admin.dashboard')}}">
										<span class="sub-item">Dashboard</span>
									</a>
								</li>
							</ul>
						</div>
					</li>
					<!-- <li class="nav-section">
						<span class="sidebar-mini-icon">
							<i class="fa fa-ellipsis-h"></i>
						</span>
						<h4 class="text-section">Clients</h4>
					</li> -->
					<li class="nav-item">
						<a data-toggle="collapse" href="#forms">
							<i class="fas fa-users"></i>
							<p>Clients</p>
							<span class="caret"></span>
						</a>
						<div class="collapse" id="forms">
							<ul class="nav nav-collapse">
								<li style="list-style-type: none;">
									<a href="{{route('clients.index')}}">
										<span class="sub-item">All Clients</span>
									</a>
								</li>
								<li>
									<a href="{{route('clients.create')}}">
										<span class="sub-item">Add Client</span>
									</a>
								</li>
							</ul>
						</div>
					</li>
					@if(auth()->user()->role == 'super_admin')
					<li class="nav-item">
						<a data-toggle="collapse" href="#admins">
							<i class="fas fa-users"></i>
							<p>Sub Admins</p>
							<span class="caret"></span>
						</a>
						<div class="collapse" id="admins">
							<ul class="nav nav-collapse">
								<li style="list-style-type: none;">
									<a href="{{route('admin.subAdmins')}}">
										<span class="sub-item">All Admins</span>
									</a>
								</li>
								<li>
									<a href="{{route('admin.createAdmin')}}">
										<span class="sub-item">Add Admin</span>
									</a>
								</li>
							</ul>
						</div>
					</li>
					@endif()
				</ul>
			</div>
		</div>
	</div>
	<!-- End Sidebar -->